### PR TITLE
Handle all events in main quic-p2p loop

### LINKED ISSUE #784: Handle all quic-p2p events in the event loop
Currently, receiving e.g. `quic_p2p::Event::UserSentMessage` produce a log printout like `Unexpected event`.

### PR DESCRIPTION
**Pull request by octol**
Resolves #784

### CODE REVIEW

File: src/vault.rs [hunk 1]
```diff
@@ -182,7 +182,13 @@ impl Vault {
             Event::NewMessage { peer_addr, msg } => {
                 return client_handler.handle_client_message(peer_addr, msg);
             }
-            event => {
+            Event::SentUserMessage { peer_addr, .. } => {
+                trace!("{}: Succesfully sent message to: {}", self, peer_addr);
+            }
+            Event::UnsentUserMessage { peer_addr, .. } => {
+                info!("{}: Not sent message to: {}", self, peer_addr);
```
Comment (nbaksalyar) [inline src/vault.rs]: A task needs to be created to handle this message in a proper way (re-sending the message if needed).
